/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Admin_JFrame.java
 *
 * Created on Jan 3, 2012, 2:57:17 PM
 */
/**
 *
 * @author 9589693153
 */
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.*;
import java.util.*;
import net.proteanit.sql.DbUtils;
public class Admin_JFrame extends javax.swing.JFrame {
 Connection conn=null;
ResultSet rs = null;
PreparedStatement pst=null;

    /** Creates new form Admin_JFrame */
    public Admin_JFrame() {
        initComponents();
        conn=ConnectionPROMA .ConnecrDb();
        CurrentDate();
        UpdateJTable();
    }
    
       public void close3() {
WindowEvent winClosingEvent = new WindowEvent( this, WindowEvent.WINDOW_CLOSING );
Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent( winClosingEvent );
}
    private void UpdateJTable(){
        
        //jTable1_pumpdata.setBackground((Color.GREEN));
         String sql="Select  *   from Employee_data ";
     
  try{
    pst =conn.prepareStatement(sql);
    rs=pst.executeQuery();
    //pst.execute();
    jTable1_pumpdata.setModel(DbUtils.resultSetToTableModel(rs));
   
    
    
    
    
    
            
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     
  }
  catch(Exception e) {
                   }
      } 

}
public void CurrentDate(){
  
  Calendar cal = new GregorianCalendar();
  int month = cal.get(Calendar.MONTH);
  int year = cal.get(Calendar.YEAR);
  int day = cal.get(Calendar.DAY_OF_MONTH);
  jMenu3.setText("Current date : "   + day + "/" + (month + 1) + "/" + year);
  //System.out.println("Current date : "  + day + "/" + (month + 1) + "/" + year);
  
     int second = cal.get(Calendar.SECOND);
     int minute = cal.get(Calendar.MINUTE);
     int hour = cal.get(Calendar.HOUR);
 Lbl_time.setText("Current time is  "+hour+" : "+minute+" : "+second);
     
      //System.out.println("Current time is  "+hour+" : "+minute+" : "+second);
  }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        cmd_SignOut = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_employeeid = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_surname = new javax.swing.JTextField();
        txt_jobtitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_division = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        txt_dob = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_userid = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        cmd_search = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cmd_add = new javax.swing.JButton();
        cmd_edit = new javax.swing.JButton();
        cmd_deleta = new javax.swing.JButton();
        cmd_clear = new javax.swing.JButton();
        cmd_refresh = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1_pumpdata = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        Lbl_time = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Admin Page");

        jToolBar1.setBackground(new java.awt.Color(204, 255, 204));
        jToolBar1.setRollover(true);

        cmd_SignOut.setFont(new java.awt.Font("Tahoma", 1, 11));
        cmd_SignOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SignOut-icon (1).png"))); // NOI18N
        cmd_SignOut.setText("Sign Out");
        cmd_SignOut.setFocusable(false);
        cmd_SignOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cmd_SignOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cmd_SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_SignOutActionPerformed(evt);
            }
        });
        jToolBar1.add(cmd_SignOut);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/print-icon.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Employee Information", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(0, 51, 204)));

        jLabel1.setText("Employee ID");

        jLabel2.setText("First Name");

        jLabel3.setText("Last Name");

        jLabel4.setText("Job Title");

        jLabel5.setText("Division");

        jLabel6.setText("Department");

        jLabel7.setText("Date of Birth");

        jLabel8.setText("Phone");

        txt_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phoneActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("User ID");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel10.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txt_password, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addComponent(txt_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_name, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txt_employeeid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txt_division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_jobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txt_department, txt_division, txt_dob, txt_employeeid, txt_jobtitle, txt_name, txt_phone, txt_surname, txt_userid});

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel9});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_employeeid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_jobtitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_division, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_dob, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_userid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Search"));

        txt_search.setText("search......");
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        cmd_search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Windows-Magnifier-icon.png"))); // NOI18N
        cmd_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_searchActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Commands", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 15), new java.awt.Color(0, 0, 153))); // NOI18N

        cmd_add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button-Add-icon.png"))); // NOI18N
        cmd_add.setText("  Add");
        cmd_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_addActionPerformed(evt);
            }
        });

        cmd_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files-Edit-file-icon (1).png"))); // NOI18N
        cmd_edit.setText("  Edit");
        cmd_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_editActionPerformed(evt);
            }
        });

        cmd_deleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bin-2-icon.png"))); // NOI18N
        cmd_deleta.setText("Delete");
        cmd_deleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deletaActionPerformed(evt);
            }
        });

        cmd_clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Actions-edit-clear-icon (1).png"))); // NOI18N
        cmd_clear.setText("Clear");
        cmd_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_clearActionPerformed(evt);
            }
        });

        cmd_refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button-Refresh-icon (1).png"))); // NOI18N
        cmd_refresh.setText("Refresh");
        cmd_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_refreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmd_edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(cmd_add, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(cmd_deleta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(cmd_clear, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(cmd_refresh, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmd_add)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_edit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_deleta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_refresh)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_search, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmd_search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cmd_search, txt_search});

        jTable1_pumpdata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1_pumpdata.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTable1_pumpdata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1_pumpdataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1_pumpdata);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu4.setText("Help");

        jMenuItem1.setText("About us");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);
        jMenu4.add(jSeparator1);

        jMenuItem2.setText("Help Desk");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu3.setForeground(new java.awt.Color(204, 0, 153));
        jMenu3.setText("Date");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jMenuBar1.add(jMenu3);

        Lbl_time.setForeground(new java.awt.Color(204, 0, 153));
        Lbl_time.setText("Time");
        Lbl_time.setFont(new java.awt.Font("Segoe UI", 1, 14));
        jMenuBar1.add(Lbl_time);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1085, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phoneActionPerformed

    private void cmd_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_addActionPerformed
        
         String sql="INSERT INTO Employee_data (EmployeeId,name,surname,Userid,password,Date_of_birth,division,department,phone,job_title) values(?,?,?,?,?,?,?,?,?,?)";
         try{
    pst =conn.prepareStatement(sql);
    pst.setString(1, txt_employeeid.getText());
    pst.setString(2, txt_name.getText());
    pst.setString(3, txt_surname.getText());
    pst.setString(4, txt_userid.getText());
     pst.setString(5, txt_password.getText());
   
    
    pst.setString(6, txt_dob.getText());
   pst.setString(7, txt_division.getText());
    pst.setString(8, txt_department.getText());
    pst.setString(9, txt_phone.getText());
     pst.setString(10, txt_jobtitle.getText());
   
   
    
   // rs=pst.executeQuery()txt_dob;
    pst.execute();
    
    JOptionPane.showMessageDialog(null, "Saved");
    //administrator_windows_JForm s = new administrator_windows_JForm();
    //s.setVisible(true);
    
    
    
    
            
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
    // conn.close();
  }
  catch(Exception e) {
                   }
      } 
    }//GEN-LAST:event_cmd_addActionPerformed

    private void cmd_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_editActionPerformed
                try{
String value1=txt_employeeid.getText();
String value2=txt_name.getText();
String value3=txt_surname.getText();
String value4=txt_userid.getText();
String value5=txt_password.getText();
String value6=txt_dob.getText();
String value7=txt_division.getText();
String value8=txt_department.getText();
String value9=txt_phone.getText();
String value10=txt_jobtitle.getText();


String sql="update employee_data set name='"+value2+"', surname='"+value3+"',userid='"+value4+"',password='"+value5+"', Date_of_birth='"+value6+"',Division='"+value7+"',department='"+value8+"', phone='"+value9+"',job_title='"+value10+"' where Employeeid='"+value1+"'"; 
pst =conn.prepareStatement(sql);
    pst.execute();
    JOptionPane.showMessageDialog(null, "Updated");
    //QueryJFrame s = new QueryJFrame();
    //s.setVisible(true);
             
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);
    }finally {
try{
  rs.close();
      pst.close();
    // conn.close();
  }
  catch(Exception e) {
                   }
      } 
    }//GEN-LAST:event_cmd_editActionPerformed

    private void cmd_deletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deletaActionPerformed
      
         String sql="delete from Employee_data where EmployeeId=?";
         try{
    pst =conn.prepareStatement(sql);
    pst.setString(1, txt_employeeid.getText());
    
   // rs=pst.executeQuery();
    pst.execute();
    
    JOptionPane.showMessageDialog(null, "Deleted");
    //QueryJFrame s = new QueryJFrame();
    //s.setVisible(true);
    
    
    
    
            
    }catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      } 
    }//GEN-LAST:event_cmd_deletaActionPerformed

    private void cmd_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_clearActionPerformed
            txt_employeeid.setText("");
        txt_name.setText("");
        txt_surname.setText("");
        
        txt_userid.setText("");
        txt_password.setText("");
        txt_department.setText("");
        txt_division.setText("");
        txt_dob.setText("");
        txt_phone.setText("");
        txt_jobtitle.setText("");
        
    }//GEN-LAST:event_cmd_clearActionPerformed

    private void cmd_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_searchActionPerformed
        
      
      
         try{
                String sql="select * from employee_data where Employeeid=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,txt_search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
    String add1=rs.getString("Employeeid");
    txt_employeeid.setText(add1);
    String add2=rs.getString("Surname");
   txt_surname.setText(add2);
   String add3=rs.getString("Name");
     txt_name.setText(add3);
    String add4=rs.getString("Job_Title");
   txt_jobtitle.setText(add4);
    
    String add5=rs.getString("Division");
    txt_division.setText(add5);
    String add6=rs.getString("Department");
   txt_department.setText(add6);
   String add7=rs.getString("Date_of_birth");
    txt_dob.setText(add7);
    String add8=rs.getString("phone");
    txt_phone.setText(add8);
    
    String add9=rs.getString("Userid");
    txt_userid.setText(add9);
    String add10=rs.getString("password");
   txt_password.setText(add10);
   
    }        
    }
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      } 
        
             try{
                String sql="select * from employee_data where Name=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,txt_search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
    String add1=rs.getString("Employeeid");
    txt_employeeid.setText(add1);
    String add2=rs.getString("Surname");
   txt_surname.setText(add2);
   String add3=rs.getString("Name");
     txt_name.setText(add3);
    String add4=rs.getString("Job_Title");
   txt_jobtitle.setText(add4);
    
    String add5=rs.getString("Division");
    txt_division.setText(add5);
    String add6=rs.getString("Department");
   txt_department.setText(add6);
   String add7=rs.getString("Date_of_birth");
    txt_dob.setText(add7);
    String add8=rs.getString("phone");
    txt_phone.setText(add8);
    
    String add9=rs.getString("Userid");
    txt_userid.setText(add9);
    String add10=rs.getString("password");
   txt_password.setText(add10);
   
    }        
    }
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
    // conn.close();
  }
  catch(Exception e) {
                   }
      } 
         
                      try{
                String sql="select * from employee_data where Surname=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,txt_search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
    String add1=rs.getString("Employeeid");
    txt_employeeid.setText(add1);
    String add2=rs.getString("Surname");
   txt_surname.setText(add2);
   String add3=rs.getString("Name");
     txt_name.setText(add3);
    String add4=rs.getString("Job_Title");
   txt_jobtitle.setText(add4);
    
    String add5=rs.getString("Division");
    txt_division.setText(add5);
    String add6=rs.getString("Department");
   txt_department.setText(add6);
   String add7=rs.getString("Date_of_birth");
    txt_dob.setText(add7);
    String add8=rs.getString("phone");
    txt_phone.setText(add8);
    
    String add9=rs.getString("Userid");
    txt_userid.setText(add9);
    String add10=rs.getString("password");
   txt_password.setText(add10);
   
    }        
    }
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      } 
             
                                try{
                String sql="select * from employee_data where Division=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,txt_search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
    String add1=rs.getString("Employeeid");
    txt_employeeid.setText(add1);
    String add2=rs.getString("Surname");
   txt_surname.setText(add2);
   String add3=rs.getString("Name");
     txt_name.setText(add3);
    String add4=rs.getString("Job_Title");
   txt_jobtitle.setText(add4);
    
    String add5=rs.getString("Division");
    txt_division.setText(add5);
    String add6=rs.getString("Department");
   txt_department.setText(add6);
   String add7=rs.getString("Date_of_birth");
    txt_dob.setText(add7);
    String add8=rs.getString("phone");
    txt_phone.setText(add8);
    
    String add9=rs.getString("Userid");
    txt_userid.setText(add9);
    String add10=rs.getString("password");
   txt_password.setText(add10);
   
    }        
    }
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);
    }finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      } 

             
    }//GEN-LAST:event_cmd_searchActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        
          if(txt_search.getText().isEmpty()){
        
            cmd_search.setBackground(Color.red);
       }else{
        
        cmd_search.setBackground(Color.GRAY);
        }
        
               try{
                String sql="select * from employee_data where Employeeid=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,txt_search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
    String add1=rs.getString("Employeeid");
    txt_employeeid.setText(add1);
    String add2=rs.getString("Surname");
   txt_surname.setText(add2);
   String add3=rs.getString("Name");
     txt_name.setText(add3);
    String add4=rs.getString("Job_Title");
   txt_jobtitle.setText(add4);
    
    String add5=rs.getString("Division");
    txt_division.setText(add5);
    String add6=rs.getString("Department");
   txt_department.setText(add6);
   String add7=rs.getString("Date_of_birth");
    txt_dob.setText(add7);
    String add8=rs.getString("phone");
    txt_phone.setText(add8);
    
    String add9=rs.getString("Userid");
    txt_userid.setText(add9);
    String add10=rs.getString("password");
   txt_password.setText(add10);
   
    }        
    }
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      } 
        
             try{
                String sql="select * from employee_data where Name=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,txt_search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
    String add1=rs.getString("Employeeid");
    txt_employeeid.setText(add1);
    String add2=rs.getString("Surname");
   txt_surname.setText(add2);
   String add3=rs.getString("Name");
     txt_name.setText(add3);
    String add4=rs.getString("Job_Title");
   txt_jobtitle.setText(add4);
    
    String add5=rs.getString("Division");
    txt_division.setText(add5);
    String add6=rs.getString("Department");
   txt_department.setText(add6);
   String add7=rs.getString("Date_of_birth");
    txt_dob.setText(add7);
    String add8=rs.getString("phone");
    txt_phone.setText(add8);
    
    String add9=rs.getString("Userid");
    txt_userid.setText(add9);
    String add10=rs.getString("password");
   txt_password.setText(add10);
   
    }        
    }
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      } 
         
                      try{
                String sql="select * from employee_data where Surname=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,txt_search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
    String add1=rs.getString("Employeeid");
    txt_employeeid.setText(add1);
    String add2=rs.getString("Surname");
   txt_surname.setText(add2);
   String add3=rs.getString("Name");
     txt_name.setText(add3);
    String add4=rs.getString("Job_Title");
   txt_jobtitle.setText(add4);
    
    String add5=rs.getString("Division");
    txt_division.setText(add5);
    String add6=rs.getString("Department");
   txt_department.setText(add6);
   String add7=rs.getString("Date_of_birth");
    txt_dob.setText(add7);
    String add8=rs.getString("phone");
    txt_phone.setText(add8);
    
    String add9=rs.getString("Userid");
    txt_userid.setText(add9);
    String add10=rs.getString("password");
   txt_password.setText(add10);
   
    }        
    }
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      } 
             
                                try{
                String sql="select * from employee_data where Division=? ";
    pst =conn.prepareStatement(sql);
   pst.setString(1,txt_search.getText());
  

    rs=pst.executeQuery();
   // pst.execute();
   if(rs.next()){
    String add1=rs.getString("Employeeid");
    txt_employeeid.setText(add1);
    String add2=rs.getString("Surname");
   txt_surname.setText(add2);
   String add3=rs.getString("Name");
     txt_name.setText(add3);
    String add4=rs.getString("Job_Title");
   txt_jobtitle.setText(add4);
    
    String add5=rs.getString("Division");
    txt_division.setText(add5);
    String add6=rs.getString("Department");
   txt_department.setText(add6);
   String add7=rs.getString("Date_of_birth");
    txt_dob.setText(add7);
    String add8=rs.getString("phone");
    txt_phone.setText(add8);
    
    String add9=rs.getString("Userid");
    txt_userid.setText(add9);
    String add10=rs.getString("password");
   txt_password.setText(add10);
   
    }        
    }
           catch(Exception e)
    {
           JOptionPane.showMessageDialog(null, e);

    }finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      } 
        
        
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void cmd_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_refreshActionPerformed
        UpdateJTable();
    }//GEN-LAST:event_cmd_refreshActionPerformed

    private void cmd_SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_SignOutActionPerformed
         try{
  rs.close();
      pst.close();
     conn.close();
  }
  catch(Exception e) {
                   }
        
        Login_PROMA_Frame s = new Login_PROMA_Frame();
    s.setVisible(true);
    

      
   close3();
   
    }//GEN-LAST:event_cmd_SignOutActionPerformed

    private void jTable1_pumpdataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1_pumpdataMouseClicked
         
      int row =jTable1_pumpdata.getSelectedRow();
      txt_employeeid.setText(jTable1_pumpdata.getModel().getValueAt(row, 0).toString());
       txt_surname.setText(jTable1_pumpdata.getModel().getValueAt(row, 1).toString());
       txt_name.setText(jTable1_pumpdata.getModel().getValueAt(row, 2).toString());
       txt_jobtitle.setText(jTable1_pumpdata.getModel().getValueAt(row, 9).toString());
        txt_division.setText(jTable1_pumpdata.getModel().getValueAt(row, 6).toString());
       txt_department.setText(jTable1_pumpdata.getModel().getValueAt(row, 7).toString());
       txt_dob.setText(jTable1_pumpdata.getModel().getValueAt(row, 5).toString());
       txt_phone.setText(jTable1_pumpdata.getModel().getValueAt(row, 8).toString());
       txt_userid.setText(jTable1_pumpdata.getModel().getValueAt(row, 3).toString());
        txt_password.setText(jTable1_pumpdata.getModel().getValueAt(row, 4).toString());
        
      
    }//GEN-LAST:event_jTable1_pumpdataMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         MessageFormat header = new MessageFormat("PROMA ");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try {
            jTable1_pumpdata.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
            //table.print(JTable.PrintMode.FIT_WIDTH, header, null);
           // jTable1_pumpdata.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }  finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      } 
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
           About_us p=new About_us();
       p.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         try                                      //try statement
     {
         Runtime.getRuntime().exec("rundll32 url.dll,FileProtocolHandler " + "C:\\Users\\9589693153\\Documents\\NetBeansProjects\\PROMA\\Frequently Asked Questions.pdf");   //open the file chart.pdf

     } catch (Exception e)                    //catch any exceptions here
       {
            JOptionPane.showMessageDialog(null,"Error");  //print the error
       }finally {
try{
  rs.close();
      pst.close();
     //conn.close();
  }
  catch(Exception e) {
                   }
      } 
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Admin_JFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Lbl_time;
    private javax.swing.JButton cmd_SignOut;
    private javax.swing.JButton cmd_add;
    private javax.swing.JButton cmd_clear;
    private javax.swing.JButton cmd_deleta;
    private javax.swing.JButton cmd_edit;
    private javax.swing.JButton cmd_refresh;
    private javax.swing.JButton cmd_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JTable jTable1_pumpdata;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_division;
    private javax.swing.JTextField txt_dob;
    private javax.swing.JTextField txt_employeeid;
    private javax.swing.JTextField txt_jobtitle;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_surname;
    private javax.swing.JTextField txt_userid;
    // End of variables declaration//GEN-END:variables
}
